services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: mmm_db
      POSTGRES_USER: mmm_user
      POSTGRES_PASSWORD: mmm_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://mmm_user:mmm_pass@db:5432/mmm_db
      - REDIS_URL=redis://redis:6379/0

  celery_worker:
    build: .
    command: celery -A bank_kpi_backend worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://mmm_user:mmm_pass@db:5432/mmm_db
      - REDIS_URL=redis://redis:6379/0

  celery_beat:
    build: .
    command: celery -A bank_kpi_backend beat -l info --scheduler django_celery_beat.schedulers.DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://mmm_user:mmm_pass@db:5432/mmm_db
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
